"""add parcel table

Revision ID: 12097446ff49
Revises: 488dcaf34561
Create Date: 2026-07-17 19:27:31.690231

"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '12097446ff49'
down_revision: str | Sequence[str] | None = '488dcaf34561'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('load_run_id', sa.Integer(), nullable=False),
                    sa.Column('source_global_id', sa.UUID(), nullable=False),
                    sa.Column('source_acres', sa.Numeric(
                        precision=12, scale=6), nullable=True),
                    sa.Column('swis_code', sa.String(
                        length=20), nullable=True),
                    sa.Column('print_key', sa.String(
                        length=255), nullable=True),
                    sa.Column('source_object_id',
                              sa.Integer(), nullable=False),
                    sa.Column('source_parcel_id', sa.String(
                        length=255), nullable=False),
                    sa.Column('property_class_code', sa.String(
                        length=50), nullable=True),
                    sa.Column('property_class', sa.String(
                        length=255), nullable=True),
                    sa.Column('municipality', sa.String(
                        length=255), nullable=False),
                    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=6535, dimension=2,
                                                                     spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
                    sa.Column('gross_acres', sa.Numeric(
                        precision=12, scale=6), nullable=False),
                    sa.Column('tax_status_date', sa.Date(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.CheckConstraint('gross_acres > 0',
                                       name='ck_parcel_gross_acres_positive'),
                    sa.ForeignKeyConstraint(
                        ['load_run_id'], ['load_run.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('source_global_id',
                                        name='uq_parcel_source_global_id')
                    )
    op.create_index('ix_parcel_geometry', 'parcel', [
                    'geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_parcel_load_run_id', 'parcel',
                    ['load_run_id'], unique=False)
    op.create_index('ix_parcel_municipality', 'parcel',
                    ['municipality'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parcel_municipality', table_name='parcel')
    op.drop_index('ix_parcel_load_run_id', table_name='parcel')
    op.drop_index('ix_parcel_geometry', table_name='parcel',
                  postgresql_using='gist')
    op.drop_table('parcel')
    # ### end Alembic commands ###
