"""add provenance tables

Revision ID: 488dcaf34561
Revises: 17163c0638a0
Create Date: 2026-07-17 14:57:44.728695

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "488dcaf34561"
down_revision: str | Sequence[str] | None = "17163c0638a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_manifest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_name", sa.String(length=255), nullable=False),
        sa.Column("source_agency", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("source_vintage", sa.String(length=100), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_crs", sa.String(length=100), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(file_sha256) = 64", name="ck_dataset_manifest_sha256_length"
        ),
        sa.CheckConstraint(
            "record_count IS NULL OR record_count >= 0",
            name="ck_dataset_manifest_record_count_nonnegative",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_sha256"),
    )
    op.create_table(
        "load_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_manifest_id", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_read", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rows_loaded", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rows_rejected", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed')",
            name="ck_load_run_status",
        ),
        sa.CheckConstraint(
            "rows_loaded >= 0", name="ck_load_run_rows_loaded_nonnegative"
        ),
        sa.CheckConstraint("rows_read >= 0", name="ck_load_run_rows_read_nonnegative"),
        sa.CheckConstraint(
            "rows_rejected >= 0", name="ck_load_run_rows_rejected_nonnegative"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_manifest_id"],
            ["dataset_manifest.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_load_run_dataset_manifest_id"),
        "load_run",
        ["dataset_manifest_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_load_run_dataset_manifest_id"), table_name="load_run")
    op.drop_table("load_run")
    op.drop_table("dataset_manifest")
    # ### end Alembic commands ###
